version : '3.8'
services:
  Bus:
    image: arisrinikhil89/paytmupi:latest
    ports:
      - "81:80"
    deploy:
      replicas: 5

  Flight:
    image: arisrinikhil89/paytmtravel:latest
    ports:
      - "82:80"
    deploy:
      replicas: 5

  Train:
    image: arisrinikhil89/paytminvestment:latest
    ports:
      - "83:80"
    deploy:
      replicas: 5

  Hotel:
    image: arisrinikhil89/paytmbills:latest
    ports:
      - "84:80"
    deploy:
      replicas: 6
